/**
 * process name (normalized) -> icon file name.
 * To add a new icon, append a new entry with the normalized process name (lowercase) as the key.
 */
export const ICON_MAP: Record<string, string> = {
  "clash for windows": "Clash-32.png",
  "unity hub": "Unity-Hub-32.png",
  acrobat: "Acrobat-32.png",
  applicationframehost: "SystemSettings-32.png",
  autohotkeyux: "AutoHotkeyUX-32.png",
  axcells: "AxCells-32.png",
  axglyph: "AxGlyph-32.png",
  axsnap: "AxSnap-32.png",
  chrome: "chrome-32.png",
  cloudmusic: "cloudmusic-32.png",
  code: "Visual-Studio-Code-32.png",
  controlpanel: "control-panel-32.png",
  cursor: "cursor-32.png",
  devenv: "Visual-Studio-32.png",
  everything: "Everything-32.png",
  excel: "EXCEL-32.png",
  explorer: "file-explorer-32.png",
  feishu: "Feishu-32.png",
  firefox: "Firefox-32.png",
  geek64: "geek64-32.png",
  geogebracalculator: "GeoGebraCalculator-32.png",
  ghelper: "GHelper-32.png",
  happ: "happ-32.png",
  idea64: "idea64-32.png",
  localsend_app: "localsend_app-32.png",
  matlab: "matlab-32.png",
  mintty: "mintty-32.png",
  msedgewebview2: "Edge-32.png",
  nanazip: "NanaZip-32.png",
  notepad: "Notepad-32.png",
  obs64: "obs64-32.png",
  obsidian: "Obsidian-32.png",
  okular: "Okular-32.png",
  origin64: "Origin64-32.png",
  memreduct: "memreduct-32.png",
  mspaint: "mspaint-32.png",
  powerpnt: "POWERPNT-32.png",
  qbittorrent: "qbittorrent-32.png",
  qq: "QQ-32.png",
  quick_any2ico: "Quick_Any2Ico-32.png",
  quicklook: "QuickLook-32.png",
  regedit: "regedit-32.png",
  sldworks: "SLDWORKS-32.png",
  snippingtool: "SnippingTool-32.png",
  spotify: "Spotify-32.png",
  steamwebhelper: "Steam-32.png",
  sublime_text: "Sublime-Text-32.png",
  taskmgr: "Taskmgr-32.png",
  trae: "Trae-32.png",
  virtualbox: "VirtualBox-32.png",
  visio: "VISIO-32.png",
  vmware: "VMware-Workstation-Pro-32.png",
  weixin: "Weixin-32.png",
  wemeetapp: "WeMeetApp-32.png",
  windhawk: "Windhawk-32.png",
  windowsterminal: "Terminal-32.png",
  winword: "WINWORD-32.png",
};

/** Base folder for icons (relative to this component's bundle output). */
export const ICON_BASE = "./assets/icons/";

/** Default icon file name when no mapping is found. */
export const DEFAULT_ICON_FILE = "Application-32.png";
